# Generated by Django 5.2.5 on 2025-09-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
